name: book manager app build application
on:
  workflow_dispatch:
env:
  WORKSPACE: book-manager-app
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'maven'
    
      - name: Build the code
        run: cd ${WORKSPACE} && mvn clean install package

      - name: Junit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Junit Test
          path: 'book-manager-app/target/surefire-reports/*.xml' 
          reporter: java-junit

      - name: Build with Maven
        run: cd ${WORKSPACE} && mvn -B verify checkstyle:checkstyle

      - name: copy check style results
        run: cp ${WORKSPACE}/target/checkstyle-result.xml checkstyle-result.xml
      
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'checkstyle-result.xml'

      - name: copy artifacts to current directory
        run: cp ${WORKSPACE}/target/bookmanager-1.0.0-SNAPSHOT.jar bookmanager.jar
         